package modelo.decks;

import modelo.Card;
import modelo.Tipo;
import modelo.tipos.Magia;
import modelo.tipos.Monstro;

public class YugiMuto {
	
	private Card ansatsu;
	private Card armadilhaDeInversao;
	private Card ataqueDeDoisGumes;
	private Card baraoDaEspadaDemoniaca;
	private Card barreiraIlusoria;
	private Card bauDeTesourosDevoradorDeHomens;
	private Card buracoArmadilha;
	private Card buracoNegro;
	private Card castorGuerreiro;
	private Card caveiraInvocada;
	private Card cemiterioDeMamutes;
	private Card destruicaoDeCards;
	private Card diabreteSelvagem;
	private Card dianKetoMestreDaCura;
	private Card domaOAnjoDoSilencio;
	private Card dragaoAladoGuardiaoDaFortalezaN1;
	private Card dragaoZumbi;
	private Card elfaMistica;
	private Card elfoAnciao;
	private Card espadaSombriaDaDestruicao;
	private Card estendeGarras;
	private Card fantasmaMagico;
	private Card fantasmaSarcastico;
	private Card feiticeiroDosCondenados;
	private Card fissura;
	private Card gaiaOCavaleiroImpetuoso;
	private Card guardiaoCelta;
	private Card insectoDevoradorDeHomens;
	private Card jarroDeCapturaDeDragoes;
	private Card livroDasArtesSecretas;
	private Card magoNegro;
	private Card maldicaoDoDragao;
	private Card mestreDasArmadilhas;
	private Card mudancaDeOpiniao;
	private Card muralhasDoCastelo;
	private Card neoOEspadachimMagico;
	private Card oGrandeBranco;
	private Card oMisticoImplacavel;
	private Card oPresaDePrata;
	private Card oferendaDerradeira;
	private Card palhacoMistico;
	private Card reforcos;
	private Card removerArmadilha;
	private Card removerMagia;
	private Card reviverMonstro;
	private Card soldadoDePedraGigante;
	private Card trocaDeAlmas;
	private Card waboku;
	private Card yami;
	
	public YugiMuto() {
		ansatsu = new Card();
		ansatsu.setCard("Ansatsu", 5, "Terra", 48365709, 1700, 1200, "Um guerreiro silencioso e mortal especializado em assassínios.");
		//armadilhaDeInversao = new Card();
		//armadilhaDeInversao.setCard("Armadilha de Inversão", null, null, 77622396, null, null, "Até a Fase Final, todos os efeitos de adcionar ou subtrair ATK ou DEF são invertidos. (Adições agora subtraem e subtrações agora adicionam. Multiplicações e divisões, incluindo efeitos de dobrar ou diminuir pela metade, não são afetados.)");
		ataqueDeDoisGumes = new Card();
		//card de Armadilha
		baraoDaEspadaDemoniaca = new Card();
		baraoDaEspadaDemoniaca.setCard("Barão da Espada Demoníaca", 4, "Trevas", 86325596, 1550, 800, "Um aristocrata que empunha uma espada possuída por um demônio, que se alimenta dos fracos.");
		barreiraIlusoria = new Card();
		barreiraIlusoria.setCard("Barreira Ilusória", 4, "Trevas", 13945284, 1000, 1850, "Se este card for atacado por um monstro, depois do cálculo de dano: devolva esse monstro para a mão.");
		bauDeTesourosDevoradorDeHomens = new Card();
		bauDeTesourosDevoradorDeHomens.setCard("Baú de Tesouros, Devorador de Homens", 4, "Trevas", 13723605, 1600, 1000, "Um monstro disfarçado de baú de tesouro e conhecido por atacar os aventureiros descuidados.");
		//buracoArmadilha = new Card();
		//buracoNegro = new Card();
		castorGuerreiro = new Card();
		castorGuerreiro.setCard("Castor Guerreiro", 4, "Terra", 32452818, 1200, 1500, "O que esta criatura falta em tamanho ele compensa em defesa quando lutando na pradaria.");
		caveiraInvocada = new Card();
		caveiraInvocada.setCard("Caveira Invocada", 6, "Trevas", 70781052, 2500, 1200, "Um demônio com poderes das trevas para confundir os inimigos. Entre os monstros do tipo demônio, é dos mais fortes.");
		cemiterioDeMamutes = new Card();
		cemiterioDeMamutes.setCard("Cemitério de Mamutes", 3, "Terra", 40374923, 1200, 800, "Um mamute que protege os túmulos do seu bando e que enfrenta ladrões de túmulos impiedosamente.");
		//destruicaoDeCards = new Card();
		diabreteSelvagem = new Card();
		diabreteSelvagem.setCard("Diabrete Selvagem", 4, "Trevas", 41392891, 1300, 1400, "Um pequeno demônio brincalhão que se esconde na escuridão, esperando para atacar um inimigo descuidado.");
		//dianKetoMestreDaCura = new Card();
		domaOAnjoDoSilencio = new Card();
		domaOAnjoDoSilencio.setCard("Doma, O Anjo do Silêncio", 5, "Trevas", 16972957, 1600, 1400, "Este anjo governa a morte e administra-a quando necessário.");
		dragaoAladoGuardiaoDaFortalezaN1 = new Card();
		dragaoAladoGuardiaoDaFortalezaN1.setCard("Dragão Alado, Guardião da Fortaleza Nº1", 4, "Vento", 87796900, 1400, 1200, "Um dragão normalmente encontrado protegendo fortalezas das montanhas. O seu ataque característico é um mergulho arrebatador vindo do céu.");
		dragaoZumbi = new Card();
		dragaoZumbi.setCard("Dragão Zumbi", 3, "Trevas", 66672569, 1600, 0, "Um dragão renascido por feitiçaria. O Seu hálito é altamete corrosivo.");
		elfaMistica = new Card();
		elfaMistica.setCard("Elfa Mística", 4, "Luz", 15025844, 800, 2000, "Uma elfa delicada com pouco poder de ataque, mas com uma incrível defesa proveniente de poderes místicos.");
		elfoAnciao = new Card();
		elfoAnciao.setCard("Elfo Ancião", 4, "Luz", 93221206, 1450, 1200, "Rumores dizem que este elfo vive há milhares de anos. Ele lidera um exército de espíritos contra seus inimigos.");
		//espadaSombriaDaDestruicao = new Card();
		estendeGarras = new Card();
		estendeGarras.setCard("Estende Garras", 3, "Trevas", 41248256, 1000, 800, "Braços que esticam e garras afiadas com lâminas fazem deste monstro um oponente formidável.");
		fantasmaMagico = new Card();
		fantasmaMagico.setCard("Fantasma Mágico", 4, "Trevas", 46474915, 1300, 1400, "Esta criatura lança uma mágica de terror de confusão logo antes de atacar seus inimigos.");
		fantasmaSarcastico = new Card();
		fantasmaSarcastico.setCard("Fantasma Sarcástico", 4, "Trevas", 36304921, 1400, 1300, "Vestido com um smoking preto como a noite, esta criatura preside à morte.");
		feiticeiroDosCondenados = new Card();
		feiticeiroDosCondenados.setCard("Feiticeiro dos Condenados", 4, "Trevas", 49218300, 1450, 1200, "Um escravo das artes das trevas, este feiticeiro é um mestre nas magias letais.");
		//fissura = new Card();
		gaiaOCavaleiroImpetuoso = new Card();
		gaiaOCavaleiroImpetuoso.setCard("Gaia, o Cavaleiro Impetuoso", 7, "Terra", 6368038, 2300, 2100, "Um cavaleiro cujo cavalo galopa mais rápido do que o vento. A sua carga de batalha é de uma força avassaladora.");
		guardiaoCelta = new Card();
		guardiaoCelta.setCard("Guardião Celta", 4, "Terra", 91152256, 1400, 1200, "Um elfo que aprendeu a empunhar uma espada, ele confunse os inimigos com ataques relâmpagos.");
		insectoDevoradorDeHomens = new Card();
		insectoDevoradorDeHomens.setCard("Insecto Devorador de Homens", 2, "Terra", 54652250, 450, 600, "VIRE: Escolha 1 monstro no campo; destrua o alvo.");
		//jarroDeCapturaDeDragoes = new Card();
		//livroDasArtesSecretas = new Card();
		magoNegro = new Card();
		magoNegro.setCard("Mago Negro", 7, "Trevas", 46986414, 2500, 2100, "O mago definitivo em termos de ataque e defesa.");
		maldicaoDoDragao = new Card();
		maldicaoDoDragao.setCard("Maldição do Dragão", 5, "Trevas", 28279543, 2000, 1500, "Um dragão perverso que se apoia nas forças das trevas para executar um poderoso ataque.");
		mestreDasArmadilhas = new Card();
		mestreDasArmadilhas.setCard("Mestre das Armadilhas", 3, "Terra", 46461247, 500, 1100, "VIRE: Destrói 1 Card de Armadilha no Campo. Se o alvo deste card está com a face para baixo, vire a face para cima. Se for um Card de Armadilha é destruído. Se não, coloque-o novamente com a face para baixo. O card virado não é ATIVADO.");
		//mudancaDeOpiniao = new Card();
		//muralhasDoCastelo = new Card();
		neoOEspadachimMagico = new Card();
		neoOEspadachimMagico.setCard("Neo, o Espadachim Mágico", 4, "Luz", 50930991, 1700, 1100, "Um viajante dimensinal que além de praticar as artes mágicas, também é um mestre com a espada e artes marciais.");
		//oferendaDerradeira = new Card();
		oGrandeBranco = new Card();
		oGrandeBranco.setCard("O Grande Branco", 4, "Água", 13429800, 1600, 800, "Um tubarão branco gigante com dentes afiados como lâminas.");
		oMisticoImplacavel = new Card();
		oMisticoImplacavel.setCard("O Místico Implacável", 4, "Luz", 87557188, 1500, 1200, "VIRE: Todos os cards no Campo com a face para baixo são virados com a face para cima e depois devolvidos à sua posição original. Os efeitos dos cards não são Ativados quando os cards são virados para cima.");
		oPresaDePrata = new Card();
		oPresaDePrata.setCard("O Presa de Prata", 3, "Terra", 90357090, 1200, 800, "Um lobo da neve que, embora agrade aos olhos, é absolutamente feroz em batalha.");
		palhacoMistico = new Card();
		palhacoMistico.setCard("Palhaço Místico", 4, "Trevas", 47060154, 1500, 1000, "Nada pode parar o ataque enlouquecido desta poderosa criatura.");
		//reforcos = new Card();
		//removerArmadilha = new Card();
		//removerMagia = new Card();
		//reviverMonstro = new Card();
		soldadoDePedraGigante = new Card();
		soldadoDePedraGigante.setCard("Soldado de Pedra Gigante", 3, "Terra", 13039848, 1300, 2000, "Um guerreiro gigante feito de pedra. Um soco desta criatura faz com que a terra estremça.");
		//testamento = new Card();
		//trocaDeAlmas = new Card();
		//waboku = new Card();
		//yami = new Card();
	}
}
